### ISSUE TITLE
Support configuration (snakecase etc)

### ISSUE THREAD

**Issue by jatcwang** [circe/circe-magnolia#14]
As mentioned in the readme, it'll be cool to have configurable derivation (snake case keys etc) like in Circe generic-extras.

I'll copy the Configuration class from generic-extras into this project. I have the it roughly working now - just cleaning it up + tests

**Comment by kevinwright** [comment]
Nice!  I was thinking to do this myself, but now I'm just going to prompt you for a PR instead :)

**Comment by jatcwang** [comment]
I've opened a PR for early feedback while I write more tests :) Comments welcome!

**Comment by jatcwang** [comment]
Fixed by https://github.com/circe/circe-magnolia/pull/24
