### ISSUE TITLE
Combine cannot be accessed in object io.circe.magnolia.derivation.decoder.semiauto

### ISSUE THREAD

**Issue by mikla** [circe/circe-magnolia#7]
Getting this error while trying to compile:

```
method combine in object semiauto cannot be accessed in object io.circe.magnolia.derivation.decoder.semiauto

[error]   val decoder = deriveMagnoliaDecoder[Foo]
[error]                                      ^

```

Here is simple project to reproduce it: https://github.com/mikla/circe-magnolia-tet 
Just try to compile it.

Thanks!

**Comment by vpavkin** [comment]
man, what a shame... Sorry about that. thanks, will take a look and fix shortly.

**Comment by vpavkin** [comment]
A quick fix: https://github.com/circe/circe-magnolia/pull/8
Will ping you when it's released :)

**Comment by vpavkin** [comment]
Please, try with 0.1.1. Worked for me :)
